apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.cronJob.name }}-clusterrole
rules:
  - apiGroups: ["velero.io"]
    resources:
     - "*"
    verbs:
     - "*"
  - apiGroups: ["*"]
    resources:
    - "secrets"
    - "codebases"
    - "gerrits"
    - "jenkins"
    - "services"
    verbs:
    - "create"
    - "get"
    - "list"
    - "watch"