apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.cronJob.name }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cronJob.name}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.cronJob.name }}-clusterrole
  apiGroup: rbac.authorization.k8s.io